export const GET_CONTACTS_START = 'GET_CONTACTS_START';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const DELETE_CONTACTS_START = 'DELETE_CONTACTS_START';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAIL = 'DELETE_CONTACTS_FAIL';

export const ADD_CONTACTS_STARTS = 'ADD_CONTACT_STARTS';
export const ADD_CONTACTS_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACTS_FAIL = 'ADD_CONTACT_FAIL';

export const EDIT_CONTACTS_STARTS = 'EDIT_CONTACT_STARTS';
export const EDIT_CONTACTS_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACTS_FAIL = 'EDIT_CONTACT_FAIL';
