#!/usr/bin/env sh
set -e
. "$(dirname -- "$0")/_/husky.sh"

echo "Hello Learn ReactJs For Tai Dev"

# Run lint-staged or other pre-commit tasks
npm run lint-staged

# Infomation for me success or error
echo "---- Oh my good prefetch 🔥 ----"

# Kiểm tra xem tệp commit message tồn tại không
if [ -f "$1" ] && [ -s "$1" ]; then
  # Lấy commit message từ tệp
  COMMIT_MESSAGE=$(cat "$1")

  # Kiểm tra xem commit message chứa "feat" hoặc "feature" không
  if echo "$COMMIT_MESSAGE" | grep -qiE "(feat|feature)"; then
    # Xuất biến môi trường để thông báo về việc tăng version
    export VERSION_BUMPED=true
    # Chạy standard-version để tăng version
    npx standard-version
  else
    # Commit message không chứa "feat" hoặc "feature"
    echo "Commit message must contain 'feat' or 'feature'."
  fi
else
  # Tệp commit message không tồn tại hoặc trống
  echo "Commit message file does not exist or is empty."
fi

# Push to remote repository (origin) on successful commit
git push origin HEAD
